### ISSUE TITLE
NODEJS 13.9

### ISSUE THREAD

**Issue by woodgieboodgie** [sfeakes/sprinklerd#18]
Once upgraded to NodeJs 13.9, sprinklerd still starts, can still switch on/off the arduino relay board zones via the GPIOs, and the 'My Sprinklers' button illuminates in Homekit.
However, the individual zone buttons themselves no longer work and if manually triggered they display 'Idle'.  this is also the case for 'run on calendar', and 'cycle all zones'.

Is there something that I need to recompile Sean or rebuild?
(had to upgrade NodeJS as other plugins needed later than 8.x)

**Comment by woodgieboodgie** [comment]
subsequent testing revealed that the zone buttons do illuminate, but not real time.   when the phone running homebridge changes to a different app and then returns to homebridge the correct zone illuminates.  however, if i was to stay on homebridge when the zone changes the app doesnt update the button (unless i leave homebridge and come back again)

**Comment by sfeakes** [comment]
If you start homebridge manually in debug mode do you get any errors on the console when turning zones on/off ?

BTW, There is nothing to re-compile in homebridge-sprinklerd, and re-compiling SprinklerD won't help as the issue is not there.

There are a few ways to put homebridge into debug mode, this is what I do.
Stop homebridge
`sudo systemctl stop homebridge`
Start debug mode on console
`sudo DEBUG=* homebridge -D -U /home/homebridge`
(change `/home/homebridge` to the directory where config.json lives)
You should get a ton of logging information.

**Comment by woodgieboodgie** [comment]
[Config] [homebridge-sprinklerd] Failed to check registry.npmjs.org for updates: Request failed with status code 404

this is the error being received
